#!/bin/sh

MATLABROOT="$1"
ARCH="$2"

if [ -n "$MATLABROOT" ]; then
    mkdir -p lib
    mkdir -p lib/bin
    mkdir -p lib/sys/os
    ln -s $MATLABROOT/java/jar/engine.jar lib
    ln -s $MATLABROOT/java/jar/mvm.jar lib
    ln -s $MATLABROOT/java/jar/util.jar lib
    ln -s $MATLABROOT/bin/$ARCH lib/bin
    ln -s $MATLABROOT/sys/os/$ARCH lib/sys/os
else
    echo "./link <MATLABROOT> <ARCH>"
fi
